Delete the point of error returning
giantswarm/test-infra pull request #115
Opened 2021-04-20 16:06 UTC by tomahawk28

2021-04-20 16:10 UTC, tomahawk28 commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
if we return the exit code here, tekton will not run `manage-sonobuoy-result` task afterward.

2021-04-21 07:58 UTC, tomahawk28 commented
sorry guys if I ping you too often :( but can you review this? thanks!

2021-04-21 08:05 UTC, MarcelMue commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
I checked this yesterday but I don't think this helps. We added this, so failed tests get reported as failed. I need to check the `manage-sonobuoy-result` task to see if that's still accurate.

2021-04-21 08:07 UTC, MarcelMue commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
Yes - it's like I remembered I think. So far we only uploaded the results on success IIRC - @fiunchinho worked on the sonobuoy tasks for azure.

What information are you missing about the failed test?

2021-04-21 08:13 UTC, MarcelMue commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
If you always want to upload to s3, you should use `finally` in your pipeline. See the `azure` pipeline for reference:

https://github.com/giantswarm/test-infra/blob/7f515f97f5e57a7c41e28b2b491330f56bebbd0d/tekton/pipelines/azure.yaml#L76

2021-04-21 09:34 UTC, tomahawk28 commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
I copied these from the `cis` task, I would fix it there, too. Thanks!

2021-04-21 12:38 UTC, fiunchinho commented on tekton/tasks/manage-sonobuoy-results.yaml
> -          exit 1
Use [the `azure` pipeline as reference](https://github.com/giantswarm/test-infra/blob/master/tekton/pipelines/azure.yaml), as that's the one we changed more recently (I think). In that pipeline you can see the use of `finally`

2021-04-21 12:39 UTC, fiunchinho requested changes
We want to mark the task as failed when tests fail, so we must keep the `exit 1`. Please, use `finally` to upload the reports like in the azure pipeline.

2021-04-21 15:15 UTC, tomahawk28 commented on tekton/pipelines/cis.yaml
> +      - name: prow-job-id
I don't know why there are differences between spacing but I would follow the `azure.yaml` as the same.

2021-04-21 15:16 UTC, tomahawk28 commented on tekton/tasks/azure.yaml
> -    type: string
This was a duplicate.

2021-04-21 15:17 UTC, tomahawk28 commented on tekton/tasks/apps.yaml
> +            --plugin-env giantswarm.CP_KUBECONFIG="$(cat /etc/kubeconfig/$(cat $(workspaces.cluster.path)/provider)) \
@fiunchinho I can't find a more elegant solution around this because I need to know the provider type as well. WDYT?

2021-04-21 16:12 UTC, MarcelMue approved these changes
LGTM if tested

2021-04-22 07:47 UTC, fiunchinho approved these changes
Sounds good!

2021-04-27 14:08 UTC, merged